build:
  commands:
    # Install dependencies from requirements.txt
    - pip install -r requirements.txt
    # Download the spaCy model
    - python -m spacy download en_core_web_sm

startCommand: gunicorn app:app
